# Automatic build and test against SugarCRM 7.X
# Push to github on success.

stages:
#    - test
#    - build
    - publish

#phpunit:
#    stage: test
#    tags:
#        - sugarcli
#    script:
#        - composer install --quiet -o
#        - php-5.3 bin/phpunit
#        - php-5.5 bin/phpunit
#        - php-5.6 bin/phpunit
#        - php -dzend_extension=/usr/lib/php5/20100525/xdebug.so bin/phpunit --color=never
#phar:
#    stage: build
#    tags:
#        - sugarcli
#    script:
#        - composer install --no-dev --quiet -o
#        - mkdir build
#        - ulimit -Sn 4096
#        - php -dphar.readonly=0 bin/box build
#    artifacts:
#        expire_in: '1w'
#        paths:
#            - build/sugarcli.phar
#mirror:
#    stage: publish
#    tags:
#        - docker
#    only:
#        - master
#    script:
#        - git push git@github.com:inetprocess/sugarcli.git HEAD:master

#mirror_tags:
#    stage: publish
#    tags:
#        - docker
#    only:
#        - tags
#    script:
#        - git push --tags git@github.com:inetprocess/sugarcli.git

gitlab_release:
    tags:
        - docker
    image: inetprocess/gitlab-release:latest
    stage: publish
    only:
        - tags
    script:
        - cp build/sugarcli.phar build/sugarcli-$CI_BUILD_TAG.phar
        - gitlab-release build/sugarcli-$CI_BUILD_TAG.phar
